export const AI_RECOMMENDATIONS: Record<number, string> = {
<<<<<<< HEAD
  0:  "Bu turda dört hissede de olumlu sinyaller alıyorum. Ancak STK3’te iç talepteki artış beklentisi daha net. O nedenle daha yüksek adet öneriyorum. Diğer hisselerde ise kontrollü bir başlangıç stratejisi benimseyebiliriz. 😊",
  1:  "STK2 ve STK3’te risk unsurları öne çıkıyor. Buna karşılık STK4’ün yurtdışı mağaza açılışları, büyüme potansiyelini artırıyor. Dağılımı bu gelişmelere paralel şekilde şekillendiriyorum.",
  2:  "Döviz kurundaki yükseliş ihracat odaklı şirketleri ön plana çıkarıyor. Bu kapsamda STK1’in avantajlı konumda olduğunu düşünüyorum ve adet önerisini arttırdım. Diğer hisselere yönelik önerilerim ise sınırlı.",
  3:  "Savunma sanayine ilişkin olumlu beklentiler STK1’i güçlendiriyor. STK3’te ise büyük çaplı ihracat sözleşmesi etkili oluyor. STK2 ve STK4’te ise temkinli davranmayı tercih etmeliyiz. 🧐",
  4:  "STK1 için uluslararası görünürlük yükselir. Buna paralel olarak hisseye olan güven artar. Diğer hisselerde ekonomik belirsizlikler ve emtia fiyatlarındaki düşüş nedeniyle öneri seviyesini düşük tutuyorum.",
  5:  "Bankacılık sektörü bu turda öne çıkıyor. STK2’de güçlü bilanço ve defansif talep artışı görülüyor. STK3’te ihracatın toparlanma sinyali verdiğini gözlemliyorum. Dengeli ama fırsatlara odaklı bir öneri sundum.",
  6:  "STK1’in bilançosu beklentilerin altında kalsa da uzun vadede potansiyel taşıyor. STK2 ve STK3’te faiz artışlarının etkisi hissediliyor. Önerilerimi bu makroekonomik gelişmelere göre sundum.",
  7:  "STK1’in yapay zeka yatırımı dikkat çekici. Bu alandaki yenilikçi adımları nedeniyle pozitif ayrışıyor. Diğer hisselerde ise sınırlı hareket alanı gözlemliyorum. Portföyünü çeşitlendirerek risk yönetimi sağlayabilirsin.",
  8:  "Devlet destekli teşvikler ve genişleyen kredi hacmi sanayi hisselerini destekliyor. STK1 ve STK3 öncelik kazanıyor. STK2’nin performansını da olumlu görebiliriz. STK4 için ise bu turda daha düşük bir öneri sunmak istedim. 😉",
  9:  "STK1 için ACN'ye teşvik beklentileri ve ihaleler fırsat yaratıyor. STK4’te KTM mağazasının büyümesi pozitif sinyaller veriyor. STK2 ve STK3’te ise beklentiler aşağı yönlü. Ağırlığı pozitif gelişmelere sahip hisselere vermeliyiz.",
  10: "Jeopolitik belirsizliklerin etkisi yüksek. Bu nedenle portföy genelinde korumacı bir yaklaşım benimsiyorum. STK3 son karlılık açıklamasının ardından önemli bir potansiyel taşıyor. STK1 ve STK4’te sınırlı alım yapılabilir düzeyde kalınmasında fayda var.",
  11: "Makro verilerdeki belirsizlik ve faiz artışları nedeniyle genel risk seviyesi yükseliyor. STK4, güçlü bilançosuna rağmen sınırlı getiri sağlayabilir. Bu nedenle önerilerimi daha temkinli bir şekilde ilerlemeliyiz 🙂", 

=======
  0: "İlk turda sektörel haber akışlarının genel olarak pozitif olduğu gözlenmektedir. STK3’te iç talep kaynaklı satış artışı belirginleşirken, STK1 için uluslararası görünürlüğü destekleyen gelişmeler etkili olmuştur. Bu çerçevede STK3’e yüksek, STK1 ve STK2’ye daha sınırlı pozisyon açılması, risk dağılımı açısından uygun görülmüştür. STK4’te ise kontrollü bir dağılım önerilmiştir.",
  1: "Piyasanın belirgin bir yön tayin etmediği bu dönemde, STK1’in yatay fiyatlaması nedeniyle pozisyonun korunması tercih edilirken, STK3 ve STK2’de olumsuz sinyaller öne çıkmıştır. STK4’teki güçlü uluslararası büyüme sinyalleri yüksek adet önerisini desteklemiştir. Bu turda defansif bir yaklaşım benimsenmiştir.",
  2: "Döviz kurlarındaki yükselişin özellikle ihracat odaklı şirketler üzerinde olumlu etkileri gözlemlenmiştir. Bu bağlamda STK1 için yüksek miktarda alım önerilmiştir. Diğer hisseler için kısa vadeli belirsizliklerin devam etmesi nedeniyle oldukça sınırlı pozisyon açılmıştır.",
  3: "STK3’te, CLK'nin önemli bir kamu ihalesinin sonuçlanması sonrası fiyat artışı beklentisi güçlenmiştir. STK1 sektörel güvenli liman özelliğini sürdürmekte ve güçlü kalmaktadır. Diğer hisseler içinse olumsuz haber akışı ve soruşturma riskleri nedeniyle sınırlı önerilerde bulunulmuştur.",
  4: "Hem global hem sektörel ölçekte olumlu görünüm STK1’de yukarı yönlü hareketi desteklemektedir. STK3’te karlılığı baskılayabilecek global fiyatlama riskleri nedeniyle düşük adet önerilmiştir. STK2 ve STK4’te ise temkinli yaklaşım sürdürülmüştür.",
  5: "BİST genelinde görülen düşüşe rağmen bankacılık sektörü pozitif ayrışmaktadır. Bu nedenle STK2’de nispeten yüksek alım önerilmiştir. STK1, STK3 ve STK4’te orta düzey alım tercih edilmiştir. Portföy dengesi gözetilmiştir.",
  6: "Bilanço beklentilerinin altında kalmasına rağmen STK1'in uzun vadeli dayanıklılığına güven duyulmaktadır. STK3 ve STK4’te makro baskılar hissedilmekte olup, STK2’de ise faiz kaynaklı düşüş beklenmektedir. Bu doğrultuda risk ayarlı pozisyonlama önerilmiştir.",
  7: "Yeni teknolojilere yapılan yatırımlar STK1’in gelecekteki potansiyelini artırmaktadır. STK3 için devlet teşvikleri ve kısa vadeli dalgalanmalardan faydalanma hedefi öne çıkmıştır. STK2 ve STK4 için mevcut piyasa riski nedeniyle sınırlı ağırlık verilmiştir.",
  8: "STK1, STK2 ve STK3 için pozitif sinyallerin devam ettiği bir dönemdir. STK4’te yatay seyir ve daha düşük büyüme beklentileri nedeniyle daha sınırlı öneri yapılmıştır. Portföyde çeşitlilik sağlanmaya devam edilmiştir.",
  9: "Devlet ihaleleri ve sektörel desteklerin artışı STK1 için güçlü pozitif sinyaller üretmektedir. STK4’te büyüme potansiyeli korunmakta, STK2’de ise olumsuz finansal sinyaller nedeniyle sınırlı alım önerilmektedir. STK3’teki global baskılar devam etmektedir.",
  10: "STK3, beklenenin üzerinde kârlılık açıklamıştır. STK1’de risk artışı öngörülmekle birlikte halen güçlü konumunu korumaktadır. STK4’te maliyet baskılarına rağmen dirençli görünüm korunurken, STK2 için getiri potansiyeli sınırlı kalmıştır.",
  11: "Piyasalarda artan belirsizlik ve jeopolitik riskler bazı hisselerde daha defansif yaklaşımı gerektirmiştir. STK2, faiz etkileriyle yeniden değerlendirilmeye açılırken, STK3 için minimum pozisyon önerilmiştir. STK1 ve STK4’te negatif sinyallere rağmen kontrollü dağılım yapılmıştır."
>>>>>>> ed5a4c47a552e4248b826074058e3e29444f7e99
};
